# Generated by Django 3.1.4 on 2020-12-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverables', '0001_initial'),
        ('workstreams', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='workstream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workstreams.workstream'),
        ),
        migrations.AddField(
            model_name='condition',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.conditiontype'),
        ),
        migrations.AddField(
            model_name='condition',
            name='deliverable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverables.deliverable'),
        ),
    ]
